### ISSUE TITLE
Some Tech reborn machines don't work

### ISSUE THREAD

**Issue by Vladyslav-Krot** [Drathonix/Nuclear-Earth-Reirradiated#1]
Don't work plate bending mache, macerator, alloy smelter,

**To Reproduce**
1. Create new world in creative mode
1. Plug-in Plate Bending Machine
2. Put In refined iron ingot

**Expected behavior**
It makes plates

**Additional context**
v 2.1.3

![Снимок](https://user-images.githubusercontent.com/25057045/115915832-35296900-a474-11eb-9fec-0cbace62fb3a.PNG)

**Comment by Drathonix** [comment]
Confirmed. I found the issue and am patching it immediately.
