### ISSUE TITLE
Semi fluid generator does not accept Tech Reborn oil

### ISSUE THREAD

**Issue by homosapien97** [Drathonix/Nuclear-Earth-Reirradiated#2]
Pack version: 2.1.3.a

EDIT: I just tried this again in a creative world, and the semi fluid generator accepted the oil. Not sure what's going on here.
EDIT 2: Breaking and moving the generator seems to have fixed the issue. Not sure what caused it in the first place, or how to reproduce.

When I attempt to put tech reborn's oil into the semi fluid generator (which JEI says I should be able to do), it won't leave its container.
-I've tried using Oil Cells
-I've tried using a bucket of oil
-I've tried putting a mekanism tank above the generator with oil in it and setting the semi fluid generator to pull from above (also tested this with creosote, which works)
**To Reproduce**
1. Create a semi fluid generator
2. Attempt to put oil into it

**Expected behavior**
Oil should be able to put into a semi fluid generator

**Comment by Drathonix** [comment]
Ok, considering that this issue solved itself, I'm going to close the issue and assume that this was just techreborn being techreborn. If you find a way to reproduce this, you can make another report with more information on how.
