### ISSUE TITLE
Power suit Ion thruster recipe broken

### ISSUE THREAD

**Issue by Marx1** [Drathonix/Nuclear-Earth-Reirradiated#4]
**Describe the bug**
Power suit Ion thruster recipe broken

![image](https://user-images.githubusercontent.com/4861651/118866973-6d677000-b897-11eb-8374-412a7e4dcaf5.png)

**Expected behavior**
Be able to craft it.

**Comment by Drathonix** [comment]
Um wtf techreborn why do you have to do this to me. Will patch next update.

**Comment by Marx1** [comment]
Forgot to say, it's in 2.1.3a and 2.1.4

**Comment by Drathonix** [comment]
Will be patched in 2.1.5 (a little late I know)
